version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
skip_tags: true
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet publish ./src/Serilog.Enrichers.Sensitive/Serilog.Enrichers.Sensitive.csproj
  - cmd: dotnet pack ./src/Serilog.Enrichers.Sensitive/Serilog.Enrichers.Sensitive.csproj
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  - cmd: dotnet test ./test/Serilog.Enrichers.Sensitive.Tests.Unit/Serilog.Enrichers.Sensitive.Tests.Unit.csproj
artifacts:
  - path: '**/*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: gH2ULaelspDrWJR3XT06/HjsKCehMkyoe/ZaEtPSvPb3vSOewlgp3CP8KW7J4m9F
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
